apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-application
spec:
  replicas: 3  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flight-application
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Define how many pods can be unavailable during the rolling update
      maxSurge: 1  # Define how many extra pods can be created during the rolling update
  template:
    metadata:
      labels:
        app: flight-application
    spec:
      containers:
        - name: flight-application
          image: ghcr.io/nus-iss-projects/flight-backend/flightbackend  # Ensure this image tag is updated in your CI/CD pipeline
          env:
            - name: AMADEUS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: amadeus-api-secrets
                  key: amadeus-api-key
            - name: AMADEUS_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: amadeus-api-secrets
                  key: amadeus-api-secret
          volumeMounts:
            - name: firebase-config
              mountPath: "/app/app/google-services.json"
              subPath: "google-services.json"
              readOnly: true
          ports:
            - containerPort: 8888
          readinessProbe:  # Define a readiness probe to check if your application is ready to serve traffic
            httpGet:
              path: /api/health  # Adjust this to the path your application uses for health checks
              port: 8888  # The port your application listens on
            initialDelaySeconds: 10  # Time to wait before the first probe is initiated
            periodSeconds: 5  # How often to perform the probe
      volumes:
        - name: firebase-config
          secret:
            secretName: firebase-config
      imagePullSecrets:
        - name: dockerconfigjson-github-com  # Secret for pulling images from GHCR
